name: CD Pipeline

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.MLOPS_CICD_SA }}

    - name: Configure docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/mlapp:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/mlapp:$GITHUB_SHA

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy wine-quality-prediction \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/mlapp:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
          
    - name: Set permissions for unauthenticated invocations
      run: |
        gcloud run services add-iam-policy-binding wine-quality-prediction \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region us-central1 \
          --platform managed